name: webhook-auto-update

on:
  repository_dispatch:
    types:
      - update-tstl

jobs:
  build:
    name: Update TSTL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.UPDATE_PAT }}
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: npm update
        run: npm update typescript-to-lua
      - name: commit update
        run: |
          git config --global user.name '41898282+github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -am "Bump tstl version"
          git push
